### ISSUE TITLE
What about .doc or .docx files?

### ISSUE THREAD

**Issue by ScientistChad** [clonemeagain/attachment_preview#14]
I attempted to open a .docx file as an iframe, however it only opens a window, doesn't actually show the document. Any suggestions on a solution, or possibly changing the file to either pdf or text?

**Comment by clonemeagain** [comment]
Older versions of osticket let anyone with the url open an attachment, so you could use Google/Office.com to embed anything like that. Now, not so much.
It's great from a security perspective though.

There's a few packages/options online for converting things into pdf, but unless you've a copy of ms word installed, they never really turn out right. I don't have a windows box to play with, but maybe a preview that's "good enough", is good enough? 

You wouldn't want to convert during view, bit of a server load, so, you could hook the mail fetch process and inject another "attachment" that is the preview. Would double up the storage used.
Haven't had any requests for it before, or chat on the forums etc. I'm thinking most folks just either block those attachments for being insecure or open them in word etc.

Maybe you can share your code? How are you trying to open it in an iframe?

**Comment by clonemeagain** [comment]
Assuming resolved.
