### ISSUE TITLE
Issue when printing

### ISSUE THREAD

**Issue by ghost** [clonemeagain/attachment_preview#15]
Hello Aaron,
thank you for your fantasitc plugin. It makes working much easier.
But I detected a small bug :-)
With enabled plugin (version 1.1 - stable) I can not print any ticket at all. The generated PDF-files don't have  any useable content and are only 1-2 kb size.
When looking at the source of the PDF, I think the generated PDF is parsed with your plugin:
Example with attachment_preview enabled: https://pastebin.com/pgDqdQEe
Example with attachment_preview disabled: https://pastebin.com/F7J0wD9M (a normal PDF-file)

Kind regards
Timo

**Comment by clonemeagain** [comment]
Hmm, might be time for another release. 
I'll check it out, thanks for the report mate!

**Comment by ghost** [comment]
I also tested the last code, same issue.
Also tested turning off PDF-preview (Inline PDF files as objects: )

**Comment by clonemeagain** [comment]
Added a patch in 9b5d0a6290e7b26325387728e89d8b40fa486353
