### ISSUE TITLE
Ticket Print No Longer Functions Correctly

### ISSUE THREAD

**Issue by tdefreest** [clonemeagain/attachment_preview#3]
After installation of this plugin, if I disable the plugin - printing works again, we can no longer print tickets. Please see images containing the issue.

**Prompt Message containing the Error:**
![prompt](https://cloud.githubusercontent.com/assets/16881887/15968214/023c1402-2ef9-11e6-8266-f0af2bb6c297.PNG)

 **Error Message:**
![error message](https://cloud.githubusercontent.com/assets/16881887/15968221/0991ee20-2ef9-11e6-8b5b-376851dc1e97.PNG)

**Additional information:**
osTicket v 1.9.12
all php extensions are activated including gdlib
If I click the drop-down arrow instead of the button, printing works perfectly.
The plug-in provides its function perfectly (Thanks!)

**Comment by clonemeagain** [comment]
I'll check it out mate, cheers for the report!

**Comment by clonemeagain** [comment]
Can you try that latest version mate? Been off sick for a while, so haven't had time to work on it, but that looks like it should fix it.

**Comment by tdefreest** [comment]
That did the trick! Thank you so much for your work on this, it has saved us so much time with the viewing of attachments.

Great work.
