### ISSUE TITLE
[feature request] Option to collapse previews

### ISSUE THREAD

**Issue by AdamDempsey** [clonemeagain/attachment_preview#30]
Once I've seen an attachment eg a PDF it obviously extends the height of the page so scrolling up and down between messages takes longer.

Could a Collapse/Expand option be added, to hide the preview once has been seen (defaulting to show obviously).

**Comment by clonemeagain** [comment]
That's certainly possible. Off the top of my head, I would think if you've actioned below, then hide. Would certainly speed things up. 
Otherwise we'd need to store that view per user per ticket either on the server or in the browser. Hmm, I'll add to my list

**Comment by clonemeagain** [comment]
I figured it out.. nice. Kinda like it. Have added to the 1.11 branch as an option. Basically, stores the ID of the ticket and any seen attachment ids that are automatically shown in the browsers localStorage cache, and if enabled, replaces those attachments that have already been seen, with the toggle button. Pretty nifty. 

Doesn't affect ones that are already toggle buttons, only auto-shown. So, if you have it set to auto-show ALL, then look at a ticket, the next time you look at it, or if you refresh, you'll see all with toggles. I'll close this now, assuming the other PR tests ok as it has this included.
