### ISSUE TITLE
not working on osticket 1.11

### ISSUE THREAD

**Issue by corent56** [clonemeagain/attachment_preview#32]
Hi,
Since the upgrade to osticket 1.11 (the file preview is all white).

Corentin

**Comment by clonemeagain** [comment]
Hmm, that's annoying. I'll have to upgrade and fix it!

**Comment by ramrajone** [comment]
It was working fine in 1.11 rc1, I had tested with PHP Ver. 7.0.33

https://forum.osticket.com/d/93565-attachment-inline-plugin-not-working
Hope it gets updated soon Thank you
while back there were some changes: 
https://github.com/clonemeagain/attachment_preview/pull/29/files/eb4ab2dd5c0f705dcee7f9f56c241830ac7ed1cc

**Comment by clonemeagain** [comment]
Hey chief, I'm super busy ATM, started a new job and there's a lot of work on. My last was really easy so I had plenty of spare time to make plugins. 
If you can test with error reporting enabled and send me the logs we might be able to diagnose and patch it sooner. 
I'm close, had to buy a new PC and it's taking time to rebuild my development environment, apparently windows 10 and docker just do not play nicely. I'll have some time coming up that should be free, so don't hold your breath or anything, but in the next few days I should be able to replicate the issue and start working on it.

**Comment by ramrajone** [comment]
I totally understand and very much appreciated your work

I will do test and send you logs

Thank you again for your support

**Comment by ramrajone** [comment]
It does not generate any errors

![image](https://user-images.githubusercontent.com/34359196/53584037-badd5280-3b50-11e9-80a1-50108d3d8be4.png)

![image](https://user-images.githubusercontent.com/34359196/53584249-363f0400-3b51-11e9-801e-d030660b2f35.png)

This message I see from working PDF preview plugin on osTicket ver. 1.10.4:
[Deprecation] HTML Imports is deprecated and will be removed in M73, around March 2019. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 for more details.

compare side by side:
![image](https://user-images.githubusercontent.com/34359196/53585685-7d7ac400-3b54-11e9-9d7e-2d0bef3eec7c.png)

let me know steps that I can do and give you more info Thanks

**Comment by clonemeagain** [comment]
Got a quickly hacked up solution, that works for FF & Chrome in 1.11:

Required setting for Firefox: https://support.mozilla.org/en-US/kb/applications-panel-set-how-firefox-handles-files
Chrome has PDF display enabled by default.

**Comment by clonemeagain** [comment]
If you want to test, please use this version: https://github.com/clonemeagain/attachment_preview/archive/1.11.zip or checkout the 1.11 branch.

I'll test it some more, then merge into master.

**Comment by ramrajone** [comment]
Hi, I just tested, chrome/Firefox worked just fine without any changes
IE/Edge .jpeg worked, but .PDF did not, which I did not expect to work nether, Thank you very much
for a quick fix


Chrome worked fine
 Version 72.0.3626.119 (Official Build) (64-bit)
Version 72.0.3626.121 (Official Build) (64-bit)

Firefox worked fine too, no changes needed:
65.0.1 (64-bit)
65.0.2 (64-bit)


IE 11
[image: image.png]

Microsoft Edge 42.17134.1.0
[image: image.png]

**Comment by clonemeagain** [comment]
Oh, yeah.
IE has never supported the technique, so much so there is an admin option
to practically insult the user for not using a better browser.

**Comment by corent56** [comment]
Thank you for the quick fix, it's working fine on chrome!

**Comment by anwoke8204** [comment]
Hello, I am having this issue with osticket 1;15;4.  I uploaded the plugin and immediately i get [Attachment Inline Plugin (defunct — missing) on the plugin page and am unable to activate the plugin.  how do I resolve this
