### ISSUE TITLE
OSTicket v1.12 (a076918) Task functionality

### ISSUE THREAD

**Issue by leandrovergara** [clonemeagain/attachment_preview#39]
On OSTicket v1.12 (a076918) Attachment Inline Plugin doesn't work with Tasks (new feature for internal issues), only for Tickets. Is there an upgrade for this new OSTicket functionality?.

**Comment by clonemeagain** [comment]
New version already? Wow.

I'll have a look, it's likely due to the plugin specifically looking for tickets URLs before doing anything.

**Comment by leandrovergara** [comment]
Your plugin is being very useful in solving our day-by-day tickets. 

Just for your information, task functionality were included in /include/class.task.php and this class is used by /include/class.thread.php.

Anything you need please tell me, I'm a PHP developer.

**Comment by leandrovergara** [comment]
Reviewing include/plugins/attachment_preview/class.AttachmentPreviewPlugin.php, I added a patch in order to use this plugin in tasks.php url. 

Original from line 1059 inside function isTicketsView(): 
`    elseif (strpos($url, 'index.php') !== FALSE ||
      strpos($url, 'tickets.php') !== FALSE) {
      // Might be a ticket page..
      $tickets_view = TRUE;
    }`

Modified:
`    elseif (strpos($url, 'index.php') !== FALSE ||
      strpos($url, 'tickets.php') !== FALSE ||
      strpos($url, 'tasks.php') !== FALSE) { 
      // Might be a ticket page..
      $tickets_view = TRUE;
    }`

**Comment by clonemeagain** [comment]
Submit a PR mate, if it works it works, ;-)

**Comment by leandrovergara** [comment]
Send pull request with changes
