### ISSUE TITLE
Feature Request: KB Attachments

### ISSUE THREAD

**Issue by clonemeagain** [clonemeagain/attachment_preview#4]
User asked for attachments to be inlined on KB articles too. 

http://osticket.com/forum/discussion/comment/106633#Comment_106633

Should be possible.  Assuming admin might want option of selecting one or the other, I've arranged a few tasks that will need to be completed to achieve this goal.

Tasks:
- [x] Add admin configuration option to enable "inline attachments for KB articles"
- [x] Write regex to find KB article URL's  combine with ticket urls. 

Additional/Extras: 
- [ ] Add admin CSS injector (For funzies). 
- [ ] textarea: Inject the following CSS into tickets pages for Staff
- [ ] textarea: Inject the following CSS into tickets pages for Customers
- [ ] textarea: Inject the following CSS into the homepage
- [ ] textarea: Inject the following CSS into the login page

**Comment by clonemeagain** [comment]
Might have to fallback to JS for KB's..

**Comment by clonemeagain** [comment]
I've been working on this, however in 1.10, it seems you can't even view attachments as a public KB user, let alone preview them..  I'll have to try with a logged-in-user. Seems annoying though. You mark a KB article as public, but it's not public for the attachments.

**Comment by mckaygerhard** [comment]
i reviewed the code of 1.10, due the development are not focused on community request due "commercial" request pprioritys, 

the attachment are not in the logic of the profiles, that why are nto possible to see it anonimously.. also the logic for load must implicts auto-url profiles too

of course that's implices too works not in the priority of the "developming osticket" and are currenlty archived as many other.. and due that many people will not spend time making pull request due the amount of rejected/forgotten pulls and contributions made..

sorry for my english, i really hate languajes.. or speak, never learned any of ones.. ..

**Comment by clonemeagain** [comment]
Can't fix.
