### ISSUE TITLE
Plugin Order needs to be correct for other plugins

### ISSUE THREAD

**Issue by t-oster** [clonemeagain/attachment_preview#51]
Hi,
I'd like to use your plugin's signal in order to append scripts to the DOM in my own plugins, since they don't seem to include my signals for that (https://github.com/osTicket/osTicket/pull/5693).

However in my test-install I cannot get the mechanism to work, because my plugin's bootstrap is called before your bootstrap and thus my call to the signal::send has vanished before your bootstrap will listen to it.

Have you considered just adding a static method instead of the signal in order to receive hooks from other plugins or is there a way to ensure correct order?

**Comment by t-oster** [comment]
..just discovered your add_arbitrary_script method... however why is it deprecated?

**Comment by clonemeagain** [comment]
Maybe plugins are executed in the order they were installed? 

Re depreciation: No idea mate, it's been a while.

**Comment by t-oster** [comment]
I tried uninstalling and re installing in some orders, but it did not work.
However since I am used to PHP-Query, I create a similar parent-plugin for my plugins which suits my needs. Thanks for that great idea, now I can reverse all my hacks on the core code and have one clean master-plugin.
